// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PerformanceOs.Infrastructure.Persistence;

#nullable disable

namespace PerformanceOs.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PerformanceOsDbContext))]
    [Migration("20260804085454_CreateCoreRecordingTables")]
    partial class CreateCoreRecordingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.Entity("PerformanceOs.Domain.TaskItems.TaskItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DefaultWorkTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("default_work_type_id");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DefaultWorkTypeId");

                    b.HasIndex("IsArchived", "UpdatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_task_items_active");

                    b.ToTable("task_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_task_items_title_not_blank", "btrim(title) <> ''");
                        });
                });

            modelBuilder.Entity("PerformanceOs.Domain.WorkSessions.PerformanceResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<short>("AccuracyLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("accuracy_level");

                    b.Property<short>("FatigueAfter")
                        .HasColumnType("smallint")
                        .HasColumnName("fatigue_after");

                    b.Property<short>("FocusLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("focus_level");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<short>("OutputLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("output_level");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<short>("SatisfactionLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("satisfaction_level");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("WorkSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("work_session_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkSessionId")
                        .IsUnique()
                        .HasDatabaseName("uq_performance_results_session");

                    b.ToTable("performance_results", null, t =>
                        {
                            t.HasCheckConstraint("ck_performance_results_accuracy", "accuracy_level BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_performance_results_fatigue", "fatigue_after BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_performance_results_focus", "focus_level BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_performance_results_output", "output_level BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_performance_results_satisfaction", "satisfaction_level BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("PerformanceOs.Domain.WorkSessions.PreWorkState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<short>("ExpectedFocusLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("expected_focus_level");

                    b.Property<short>("FatigueLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("fatigue_level");

                    b.Property<short>("MoodLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("mood_level");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<long>("WorkSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("work_session_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkSessionId")
                        .IsUnique()
                        .HasDatabaseName("uq_pre_work_states_session");

                    b.ToTable("pre_work_states", null, t =>
                        {
                            t.HasCheckConstraint("ck_pre_work_states_expected", "expected_focus_level BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_pre_work_states_fatigue", "fatigue_level BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_pre_work_states_mood", "mood_level BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("PerformanceOs.Domain.WorkSessions.WorkContext", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("InterruptionExpected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("interruption_expected");

                    b.Property<string>("LocationNote")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location_note");

                    b.Property<int>("MeetingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("meeting_count");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("WorkLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("work_location");

                    b.Property<long>("WorkSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("work_session_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkSessionId")
                        .IsUnique()
                        .HasDatabaseName("uq_work_contexts_session");

                    b.ToTable("work_contexts", null, t =>
                        {
                            t.HasCheckConstraint("ck_work_contexts_location", "work_location IN ('Home','Office','Cafe','Other')");

                            t.HasCheckConstraint("ck_work_contexts_location_note", "location_note IS NULL OR work_location = 'Other'");

                            t.HasCheckConstraint("ck_work_contexts_meeting", "meeting_count >= 0");
                        });
                });

            modelBuilder.Entity("PerformanceOs.Domain.WorkSessions.WorkSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("AbandonNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("abandon_note");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("InterruptionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("interruption_count");

                    b.Property<long?>("PlannedWorkId")
                        .HasColumnType("bigint")
                        .HasColumnName("planned_work_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<long>("TaskItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_item_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("WorkTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("work_type_id");

                    b.HasKey("Id");

                    b.HasIndex("PlannedWorkId")
                        .IsUnique()
                        .HasDatabaseName("uq_work_sessions_planned_work");

                    b.HasIndex("StartedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_work_sessions_started_at");

                    b.HasIndex("TaskItemId", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_work_sessions_task_item");

                    b.HasIndex("WorkTypeId", "StartedAt")
                        .HasDatabaseName("ix_work_sessions_work_type");

                    b.ToTable("work_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_work_sessions_abandon_note", "abandon_note IS NULL OR status = 'Abandoned'");

                            t.HasCheckConstraint("ck_work_sessions_interruption", "interruption_count >= 0");

                            t.HasCheckConstraint("ck_work_sessions_period", "finished_at IS NULL OR finished_at > started_at");

                            t.HasCheckConstraint("ck_work_sessions_status_finished", "(status = 'InProgress' AND finished_at IS NULL)\nOR (status IN ('Completed','Abandoned') AND finished_at IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("PerformanceOs.Domain.WorkTypes.WorkType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "DisplayOrder")
                        .HasDatabaseName("ix_work_types_active_order");

                    b.ToTable("work_types", null, t =>
                        {
                            t.HasCheckConstraint("ck_work_types_name_not_blank", "btrim(name) <> ''");
                        });
                });

            modelBuilder.Entity("PerformanceOs.Domain.TaskItems.TaskItem", b =>
                {
                    b.HasOne("PerformanceOs.Domain.WorkTypes.WorkType", null)
                        .WithMany()
                        .HasForeignKey("DefaultWorkTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_items_default_work_type");
                });

            modelBuilder.Entity("PerformanceOs.Domain.WorkSessions.PerformanceResult", b =>
                {
                    b.HasOne("PerformanceOs.Domain.WorkSessions.WorkSession", null)
                        .WithOne("Result")
                        .HasForeignKey("PerformanceOs.Domain.WorkSessions.PerformanceResult", "WorkSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_performance_results_work_session");
                });

            modelBuilder.Entity("PerformanceOs.Domain.WorkSessions.PreWorkState", b =>
                {
                    b.HasOne("PerformanceOs.Domain.WorkSessions.WorkSession", null)
                        .WithOne("PreWorkState")
                        .HasForeignKey("PerformanceOs.Domain.WorkSessions.PreWorkState", "WorkSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pre_work_states_work_session");
                });

            modelBuilder.Entity("PerformanceOs.Domain.WorkSessions.WorkContext", b =>
                {
                    b.HasOne("PerformanceOs.Domain.WorkSessions.WorkSession", null)
                        .WithOne("WorkContext")
                        .HasForeignKey("PerformanceOs.Domain.WorkSessions.WorkContext", "WorkSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_contexts_work_session");
                });

            modelBuilder.Entity("PerformanceOs.Domain.WorkSessions.WorkSession", b =>
                {
                    b.HasOne("PerformanceOs.Domain.TaskItems.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_sessions_task_item");

                    b.HasOne("PerformanceOs.Domain.WorkTypes.WorkType", null)
                        .WithMany()
                        .HasForeignKey("WorkTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_sessions_work_type");
                });

            modelBuilder.Entity("PerformanceOs.Domain.WorkSessions.WorkSession", b =>
                {
                    b.Navigation("PreWorkState")
                        .IsRequired();

                    b.Navigation("Result");

                    b.Navigation("WorkContext")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
